= Venta de entradas por PayPal

:hp-tags: Ditirambo, GGLAM, MDIPAYA, Manual de instrucciones para amar y asesinar, musicales, entradas, venta

¡Hola a todos!

Después de mucho tiempo de inactividad en la web (no así https://www.facebook.com/coralditirambo/[en nuestra página de Facebook] o https://www.instagram.com/coralditirambo/[en nuestro perfil en Instagram]), os anunciamos que contamos con una cuenta de PayPal a través de la cual podréis pagar las entradas que pongamos a la venta. PayPal es un intermediario de pago muy conocido por su seguridad a la hora de realizar pagos por Internet, por lo que ya no tenéis excusa para no comprarnos vuestras entradas desde casa. :)

Para pagar por PayPal es necesario tener una cuenta en el servicio y dar de alta una cuenta corriente o tarjeta bancaria, operaciones muy sencillas de hacer. Una vez tengáis vuestra cuenta, solo tendréis que https://www.paypal.com/es/webapps/mpp/send-money-online[entrar a este enlace] y poner como correo electrónico destinatario ditirambo@ditirambo.es.

Si tenéis cualquier duda sobre cómo hacer estos pagos, avisadnos por la página de Facebook y trataremos de solucionarlos y resolverlos lo mejor posible, así como de dejarlo mejor explicado lo que no se entienda bien.

¡Nos vemos en los escenarios!