= Venta de entradas por PayPal

:hp-tags: Ditirambo, pago, entradas, venta, PayPal

== ¿Qué es PayPal?

https://www.paypal.com[Paypal] es un sistema de pagos a través de Internet que permite a sus usuarios realizar transferencias y pagos sin necesidad de compartir datos bancarios. Alcanzó gran éxito como medio de pago seguro en https://www.ebay.com[eBay] y, desde hace años, muchas personas y compañías aceptan pagos a través de este medio.

== ¿Qué necesito para pagar por PayPal?

Para pagar por PayPal solo necesitas hacerte una cuenta en el servicio en la que introducir una cuenta bancaria o una tarjeta como medio de pago (y cobro, en su caso). El proceso de alta es sencillo y la verificación segura de los medio de pago se hace mediante pequeños ingresos (céntimos) que te envía PayPal para que puedas confirmar que realmente tienes acceso al sistema de pago que estás añadiendo.

Una vez tengas añadido al menos un medio de pago, tendrás todo listo para poder hacernos pagos a través de PayPal.

== ¿Cómo os envío dinero?

* Accede a https://www.paypal.com/es/webapps/mpp/send-money-online[este enlace].
* Introduce como correo electrónico del destinatario del pago: ditirambo@ditirambo.es.
* Incluye la cantidad que deseas enviar.
* Sigue el resto de pasos que te indica PayPal para confirmar y ¡ya lo tienes!